### ISSUE TITLE
No sql database/installer on branch chivalry-is-dead-game

### ISSUE THREAD

**Issue by lucasmaffei** [MasterGeneral156/chivalry-engine#110]
Hello, I saw that in the repository(https://github.com/rykas-productions/chivalry-engine/tree/chivalry-is-dead-game) has no installer or SQL file, please, where can I get? I would like to study the full game. Thanks ;)

**Comment by MasterGeneral156** [comment]
I really won't be sharing my game's SQL file, you know?
