### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by wizwych** [MasterGeneral156/chivalry-engine#112]
your Chivalry website wont allow users to register as of 27th Dec 2021

364: Field 'signature' doesn't have a default value Attempted to execute query: INSERT INTO `users`
(`username`,`email`,`password`,`level`,`gender`,`class`,
`lastip`,`registerip`,`registertime`,`loginip`,`display_pic`,`vip_days`)

**Comment by MasterGeneral156** [comment]
``$db->query("set GLOBAL sql_mode='ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'");``

Running this fixes it. Super dirty, and won't persist a server reset.
