### ISSUE TITLE
Item Group Name - Persistant Cross Site Scripting 

### ISSUE THREAD

**Issue by ThatIcyChill** [MasterGeneral156/chivalry-engine#19]
Gets executed when creating an item on page load of create an item after the group has been created,

Tested locally as x10 host has some protections in place against these type of attacks.

**Comment by MasterGeneral156** [comment]
Clarify the steps you did, please.

**Comment by ThatIcyChill** [comment]
No worries , I thought it may be easier to show with a video- https://www.sendspace.com/file/d9kbmj
