### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by MasterGeneral156** [MasterGeneral156/chivalry-engine#33]
Right, so, there hasn't been much heard from me in the past long while concerning where I want things to go with this. I promise you I'm still working on this. Slowly, but I still am.

My main concern is getting everything fully localized. Followed next will be finishing planned additions/features. Afterwards will involve a private alpha where we security audit the hell out of the engine. Once this has concluded, and any and all bugs are squished, we'll be able to finally put this into a live instance!

I've been committed to keeping security a priority, and I will not cheap out on this. Thank you, and have a good evening folks.

**Comment by Oroton** [comment]
excitied to see how this works, I've played around with a lot of engine but its good to see someone that hasn't abandoned one 5 years ago.
