### ISSUE TITLE
on install.php

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#34]
Uploaded files to server, 
went to installer.php

1. Diagnostics >> 2. Configuration >> 3. Installation & Extras

This is all that is displayed

**Comment by MasterGeneral156** [comment]
Heh heh. Oops.

Uploading a fix now.

**Comment by MasterGeneral156** [comment]
Let me know if that fixes it or not.

**Comment by MasterGeneral156** [comment]
Closing since no response. Please open a new issue if this still persists.
