### ISSUE TITLE
Guild Warring Ideas

### ISSUE THREAD

**Issue by MasterGeneral156** [MasterGeneral156/chivalry-engine#35]
I'm not too sure how I wish to handle guild wars. In other engines, its handled by losing points/respect whenever one of your guild mates falls in battle, and the war continues indefinitely until either guild reaches zero points.

I was playing around with the idea of a war period being 72 hours in length (changeable via staff panel), and it being accumulative points. The guild with the most points after the time period is up, is the winner of this war.

Of course, there's two reasons to war other guilds. For guild experience/levels, and the privilege to claim a town under control by your guild. Controlling a town will allow you to set tax rates on that town, and leveling your guild allows you to increase your guild's vault size, guild gym output and guild member capacity, so it IS worthwhile to war.

Any thoughts/concerns/questions?

**Comment by Oroton** [comment]
I like this idea, it's pretty consistant with the genre.

I made modifications for the ADR engine on PHPBB2 and one was the government mod.

it was pretty indepth but to simplify it this is how it worked.

I could group zones under a "Town"
and then group "Towns" into "States" and then have "States" in "Countries"

The ruler of the capital "Town" of the Capital "State" became ruler of the country.

All Towns had Mayors, States had Commanders and all Countries had Kings.
All NPC's that received a particular item or power to use in battle.
If you challenged that NPC to war, and won you became king. then you could be challenged.
While 'defending' your title or fighting in your "town/state/country" you were able to use the item. 

That is basically how that worked.

It gave other Guilds/Clans a reason to fight for things themselves. Each Mayor of a town, earned a tax based on the items players bought in each town. But then each mayor had to pay tax to the state. and each commander paid a tax to the king.

Not the same thing but an idea that could run along side yours.

You could fight other guilds to usurp the current leader of that town and if you win earn what ever reward.

however you can reset it the next week. 

Guilds can earn points by mulitple things. completing quests and/or fights or it's own event..
