### ISSUE TITLE
focus

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#37]
What area's are you working on at the moment?

Personally i'd like to see a working admin panel. 
Where you can give currency and make changes to users as a minimum

But with a module system,

This will allow others like myself, a good platform for how you want the core to look, so when we work on a model say, smelting, fishing, guilds, mining, battles, or anything that isn't complete.
just a thought.

My coding is very old school, php4 but I will do my best to use yours as a guide

**Comment by MasterGeneral156** [comment]
There's a staff panel. Is that what you mean? Accessible via <yoururl>/staff/index.php. You can do a lot of things here, its probably still missing some pages, but they're likely for things I have yet to complete elsewhere in-game.

I was working on the guilds, but I'm probably going to knock some smaller things out, like the markets/auction. If you have an idea or something, go ahead and make it happen. I'm all eyes and ears.

**Comment by Oroton** [comment]
ah, 
error in the link It takes you to 
staff/
but not staff/index.php.
I should change my htaccess back to auto to index.php, but just thought I'd share that.

I thought i'd work on adding a template system to your engine, take all the hardcode out, leave it as vanilla as possible.

**Comment by MasterGeneral156** [comment]
Oh, good point about the auto index.php. Will plug in a patch for that in a few moments.

I'm all for a template system as long as its remain compatible with Bootstrap and/or is mobile friendly.

**Comment by Oroton** [comment]
I've already done a pull request for you to see.
The template engine is very light weight.
It won't change your structure at all,
It basically moves all the html to an external file. Refers all hardcoded words back the the main file, which Points to the lang files.
Other than that your engine is exactly the same. Will eventually move the .css files to each template. So that it's individual to the template, but long road a head removing all the hardcoded html.
