### ISSUE TITLE
Your data in your database

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#38]
Because you don't have an admin panel.

manually going through the database, to add in items, and shops, and all the rest. May i suggest you make an SQL file with all your data, that others can use to populate their database with to test the game.

**Comment by MasterGeneral156** [comment]
Well, truthfully, I don't have much of a database locally for my testing, either. A few test items, a few test users, a test guild and a test mine.

Also, as said in the other thread, the staff/admin panel's accessible via <yoururl>/staff/index.php. The other way to get to it is clicking that "Hello, <your name>" dropdown. If you have staff privileges, it'll be listed there. If not, I'll have to double check some things in the installer.
