### ISSUE TITLE
staff_towns.php?action=edittown

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#41]
Error in staff panel, for editing towns,

Can create and delete towns but not edit

**Comment by MasterGeneral156** [comment]
A lot of the staff panel is incomplete, and editing towns is one of those things. I can rush it out right now, if desired.

**Comment by Oroton** [comment]
Its 1:30am at the moment.. I'm about to go to bed, 
i'm just playing around with everything, trying to get a feel for it.

**Comment by MasterGeneral156** [comment]
Go to bed and I'll try to square these things away before you wake up. :P
