### ISSUE TITLE
Go back button

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#42]
I think the most frustrating think is there is no 
Continue or back button or autorefresh,

For instance, you purchase something there is not
"Back to shop" 
or 2 second reload and refresh the page.

Or when you are doing any changes in staff panel, there is no continue forward icon/button

Back to shop works well, 

Also new to Github, so not sure how to just make suggestions/comments without making an issue

**Comment by MasterGeneral156** [comment]
Honestly, this is the one thing I've heard most back when I had the first alpha a few months ago. Still strikes me odd as to why I hadn't fixed this. I'll ponder over this for a few minutes, and add how I want to do this. Probably going to route of auto-redirect.

**Comment by Oroton** [comment]
A clean way, would be to auto reload with a transitional 
<div> loading over the page.. then fading out.
you could do this by 
every page running a function to load a transitional message if there is a message.
and then populate that image with what you just completed.

**Comment by Oroton** [comment]
also I just added suggested this engine to thread on
indie-resource.com forum for the List of Browser engines.

Great community for indie developers.

**Comment by MasterGeneral156** [comment]
The back button was added in 5d188b9d3f86e620b6793c2feee6e63a6cebe118. However, note that this will temporarily just redirect you back to index.php until I can go over each page and add in the real redirect link per alert.

**Comment by Oroton** [comment]
made the button go back to original page using $_SERVER['REQUEST_URI']

**Comment by MasterGeneral156** [comment]
Biggest. Facepalm. Ever.

**Comment by MasterGeneral156** [comment]
Haha. You're right! Love how awake I am, eh?

**Comment by Oroton** [comment]
I took you advice I'm in bed. Good night.

**Comment by MasterGeneral156** [comment]
See you around!

**Comment by MasterGeneral156** [comment]
Added in PR #43
