### ISSUE TITLE
SQL Changes to update DB for new versions

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#44]
Couldn't find an update Database script for the changes made

example,,

1146: Table 'chivalry.pw_recovery' doesn't exist

**Comment by MasterGeneral156** [comment]
CREATE TABLE `pw_recovery` (
  `pwr_id` int(11) UNSIGNED NOT NULL,
  `pwr_ip` text NOT NULL,
  `pwr_email` text NOT NULL,
  `pwr_code` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `pw_recovery`
ADD PRIMARY KEY (`pwr_id`);

ALTER TABLE `pw_recovery`
MODIFY `pwr_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE `pw_recovery` 
ADD `pwr_expire` INT(11) UNSIGNED NOT NULL AFTER `pwr_code`;

**Comment by Oroton** [comment]
done
