### ISSUE TITLE
Started a fresh site, and came across install error

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#46]
A critical error has occurred, and installation has stopped. Below are the details:
1231: Variable 'character_set_client' can't be set to the value of 'NULL'

Action taken: Attempted to execute query: /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

Context at error time: 

Array
(
[0] => Array
(
[file] => /hermes/bosnaweb17a/b633/ipg.brcadmin/chivtest/installer.php
[line] => 498
[function] => query
[class] => database
[type] => ->
[args] => Array
(
[0] => /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
)

)

[1] => Array
(
[file] => /hermes/bosnaweb17a/b633/ipg.brcadmin/chivtest/installer.php
[line] => 26
[function] => install
[args] => Array
(
)

)

)

**Comment by MasterGeneral156** [comment]
I think I know the issue with this. Lemme double check haha.

**Comment by MasterGeneral156** [comment]
Its 1 AM, so I think I probably, messed something up with the fix. If so, I'll fix when I wake up. haha.

**Comment by Oroton** [comment]
another error after adding your fix

nstaller Error

A critical error has occurred, and installation has stopped. Below are the details:
1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-CREATE TABLE `enemy` ( `enemy_id` int(11) UNSIGNED NOT NULL, `enemy_user` int' at line 1

Action taken: Attempted to execute query: -CREATE TABLE `enemy` ( `enemy_id` int(11) UNSIGNED NOT NULL, `enemy_user` int(11) UNSIGNED NOT NULL, `enemy_adder` int(11) UNSIGNED NOT NULL, `comment` text NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;

Context at error time: 

Array
(
[0] => Array
(
[file] => /hermes/bosnaweb17a/b633/ipg.brcadmin/chivtest/installer.php
[line] => 498
[function] => query
[class] => database
[type] => ->
[args] => Array
(
[0] => -CREATE TABLE `enemy` ( `enemy_id` int(11) UNSIGNED NOT NULL, `enemy_user` int(11) UNSIGNED NOT NULL, `enemy_adder` int(11) UNSIGNED NOT NULL, `comment` text NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
)

)

[1] => Array
(
[file] => /hermes/bosnaweb17a/b633/ipg.brcadmin/chivtest/installer.php
[line] => 26
[function] => install
[args] => Array
(
)

)

)
