### ISSUE TITLE
errror when changing avatar

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#48]
Chivalry Test Site - Critical Error
A critical error has occurred, and page execution has stopped. If this issue persists, please notify an admin or web developer right away!
Below are the details:
PHP Warning: getimagesize(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 (2)

Action taken: Line executed: /hermes/bosnaweb17a/b633/ipg.brcadmin/chivtest/global_func.php:77

**Comment by MasterGeneral156** [comment]
I'll have to play around with this later.
