### ISSUE TITLE
Academy

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#50]
Error while studying in academy

1054: Unknown column 'course' in 'field list'

Action taken: Attempted to execute query: update `users` SET `course`='1' WHERE `userid` = '1

**Comment by Oroton** [comment]
Also Missing, 

`days_left` column in user tabs..

 Course Successfully Started! 
you have started the course Academy 1.
It will finish in 1 day(s) > Go Back

The Go Back button here points to 
academy.php?action=start&id=1

**Comment by MasterGeneral156** [comment]
I swear to god I've removed that days left query like 5 times now. >_< The academy itself was done by another person, and I don't care for how it was done, so its pending a rewrite. For the most part, errors on it should be ignored more-or-less.

**Comment by Oroton** [comment]
Ok I will skip it completely. For the templates
If u do rewrite it use the template system. No hardcore ;)

**Comment by MasterGeneral156** [comment]
I'll try my best. haha.

**Comment by Oroton** [comment]
I actually just added them to the user table, but obviously nothing really works

**Comment by MasterGeneral156** [comment]
Disabled the queries in 416d659ca6803009f78b74987e46756594f1e397
