### ISSUE TITLE
Version 1.0 says its Version 0.4.1

### ISSUE THREAD

**Issue by Oroton** [MasterGeneral156/chivalry-engine#72]
As title says, 

Version 1.0 says its version 0.0.4.1

**Comment by MasterGeneral156** [comment]
According to my source, it doesn't. Did you just drag-and-drop the changes from the latest on-top of your files? That won't update the version numbering, but it WILL update the files at the very least. I have version numbering saved in database, I might end up changing that for ease-of-use sake.

**Comment by Oroton** [comment]
no this is from a vanilla install.

new database, new files

**Comment by Oroton** [comment]
ill check i used the right files..

**Comment by Oroton** [comment]
yep, i installed from the wrong folder..

**Comment by MasterGeneral156** [comment]
Well dang. That'll get ya! :D Is this okay to close now?
