### ISSUE TITLE
Fatal error: Call to undefined function edittown() 

### ISSUE THREAD

**Issue by ThatIcyChill** [MasterGeneral156/chivalry-engine#76]
**Page Causing Issue:**  /staff/staff_towns.php?action=edittown
**Error Log (Use Pastebin):**  https://pastebin.com/MQgrA3Q6
**Line Errored:**  20
**What You Expected:**  Be able to edit town
**What REALLY Happened:**  Returned - 
Fatal error: Call to undefined function edittown() in C:\xampp\htdocs\staff\staff_towns.php on line 20 as shown in the pastebin log.
**Any Other Info:**

**Comment by MasterGeneral156** [comment]
Not added yet. :P
