### ISSUE TITLE
Crime Experience

### ISSUE THREAD

**Issue by BrisbaneGamer** [MasterGeneral156/chivalry-engine#86]
This isn't an issue, just wanting to confirm whether my understanding of crime experience is correct?

So with the default formula: ((WILL*0.8)/2.5)+(LEVEL/4)

Assuming that you have 100 will and are level 1, this would be:

((100*0.8)/2.5)+(1/4) = 32.25

So does this mean that the crime success rate is 32.25%?

Are you able to elaborate on how you came up with this particular formula? Thanks.

**Comment by MasterGeneral156** [comment]
It's just a starter/placeholder formula to give you an idea of what you can use. As your level/will increases, you'll see that formula's chance for success increases. As you see [here](https://github.com/MasterGeneral156/chivalry-engine/blob/f532012ebf9adfb1405e4a1af8ebcb2fedd619bb/upload/criminal.php#L109), you can input LEVEL, EXP, WILL, IQ.

In all actuality, you could probably make a very complex formula such as
(((IQ*LEVEL)/EXP)/WILL) or, your own random formula. You should be able to, in theory, also just enter in a flat number if you want _everyone_ to only have a specific chance of success.
